name: Docker Deploy

on:
  push:
    branches:
      - docker-deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configuração do Docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construção da imagem Docker
        run: docker build -t my-node-app .

      - name: Push da imagem para o DockerHub
        run: docker push my-node-app
